name: Build Android APK
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Ekstrak File ZIP
      run: unzip *.zip -d .
      
    - name: Perbaiki Isu Keystore
      run: sed -i 's/signingConfig = signingConfigs.getByName("debugConfig")//g' app/build.gradle.kts
      
    - name: Siapkan Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Build APK (Sistem Bawaan)
      run: gradle assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        
